  name: Sync Image to Aliyun  Example

  on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Git pull
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2.9.1

        - name: Login to Docker Hub
          uses: docker/login-action@v2.2.0
          with:
            registry: registry.cn-hangzhou.aliyuncs.com
            username: 军师祭酒zzz
            password: liuyin141
            logout: false

        - name: Use Skopeo Tools Sync Image to Docker Hub
          run: |
            skopeo copy docker://registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407@sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b docker://registry.cn-hangzhou.aliyuncs.com/dkims/kube-webhook-certgen
